name: creatorradar
version: '1.0.0'
config-version: 2

profile: creatorradar

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  creatorradar:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
