brand_keywords:
  - The Purest Solutions
  - La Roche-Posay
  - CeraVe
  - Bioderma
  - Garnier
  - Maybelline
  - L'Oréal
  - Yves Rocher
  - Sephora
  - Gratis
  - Watsons
  - Bee Beauty
  - Pastel
  - Flormar
  - Note
  - Revolution
  - Nivea
  - Neutrogena
  - Sebamed
  - Cosmed
